### ISSUE TITLE
Cannot import name MonitoringPlugin

### ISSUE THREAD

**Issue by fr05t1k** [yandex-load/yatank-online#11]
I have a problem with this plugin. Could you help with it?

```
[tank]
plugin_web=yatank_OnlineReport
```
```
17:46:07 [WARNING] /etc/yandex-tank is not accessible to get configs list
17:46:07 [INFO] No config passed via cmdline, using ./load.ini
17:46:07 [INFO] Loading configs...
17:46:07 [INFO] Loading plugins...
17:46:07 [INFO] Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 222, in configure
    self.core.load_plugins()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 160, in load_plugins
    plugin = il.import_module(plugin_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/yatank_OnlineReport/__init__.py", line 1, in <module>
    from plugin import OnlineReportPlugin as yatank_OnlineReportPlugin
  File "/usr/local/lib/python2.7/dist-packages/yatank_OnlineReport/plugin.py", line 4, in <module>
    from yandextank.plugins.Monitoring import MonitoringPlugin
ImportError: cannot import name MonitoringPlugin
```
```
ansible (1.7.2)
backports-abc (0.5)
certifi (2016.9.26)
cffi (1.9.1)
chardet (2.3.0)
colorama (0.3.2)
configparser (3.5.0)
cryptography (1.6)
defusedxml (0.4.1)
docutils (0.12)
ecdsa (0.11)
enum34 (1.1.6)
future (0.16.0)
html5lib (0.999)
httplib2 (0.9)
idna (2.1)
iotop (0.6)
ipaddress (1.0.17)
Jinja2 (2.7.3)
MarkupSafe (0.23)
ndg-httpsclient (0.3.2)
numpy (1.11.2)
pandas (0.19.1)
paramiko (2.0.2)
Pillow (2.6.1)
pip (9.0.1)
ply (3.4)
psutil (5.0.0)
pyasn1 (0.1.9)
pycparser (2.10)
pycrypto (2.6.1)
Pygments (2.0.1)
pyjade (4.0.0)
pyOpenSSL (0.14)
python-apt (0.9.3.11)
python-dateutil (2.6.0)
python-debian (0.1.27)
python-debianbts (1.11)
pytz (2016.7)
PyYAML (3.11)
reportbug (6.6.3)
requests (2.12.1)
roman (2.0.0)
setuptools (28.8.0)
simplejson (3.10.0)
singledispatch (3.4.0.3)
six (1.8.0)
SOAPpy (0.12.22)
TornadIO2 (0.0.4)
tornado (4.4.2)
urllib3 (1.9.1)
wheel (0.24.0)
wstools (0.4.3)
yandextank (1.8.27)
yatank-online (0.0.9)
```

**Comment by fr05t1k** [comment]
This plugin doesn't work with 1.8.* version yandex-tank. With 1.7 works fine.

**Comment by direvius** [comment]
Yes, the 1.8 version is not ready yet. Use overload.yandex.net for reporting.
